parameters:
- name: NpmPackagingMode
  displayName: 'NPM packages publish configuration'
  type: string
  default: 'dev'
- name: IsReleasePipeline
  displayName: 'Npm packaging pipeline'
  type: boolean
  default: false
- name: PoolName
  displayName: 'Agent pool name'
  type: string
  default: 'onnxruntime-Win-CPU-2022'
- name: PackageName
  displayName: 'Package name'
  type: string
  default: 'NPM_packages'
- name: BuildStaticLib
  displayName: 'Build static library'
  type: boolean
  default: false
- name: BuildJsep
  displayName: 'Build JSEP'
  type: boolean
  default: true

- name: ExtraBuildArgs
  displayName: 'Extra build command line arguments'
  type: string


stages:
- stage: Extract_commit
  jobs:
  - job: Extract_commit
    pool: ${{ parameters.PoolName }}
    variables:
      runCodesignValidationInjection: false
    timeoutInMinutes: 30
    workspace:
      clean: all
    steps:
    - checkout: none
      fetchDepth: 1
      submodules: false
    - script: |
        echo.$(Build.SourceVersion)
        echo.$(Build.SourceVersion)>$(Build.ArtifactStagingDirectory)\__commit.txt
    - task: PublishPipelineArtifact@0
      displayName: 'Publish Pipeline Artifact'
      inputs:
        artifactName: '__commit'
        targetPath: '$(Build.ArtifactStagingDirectory)'

- stage: Build_wasm_Release_static_library
  dependsOn: Extract_commit
  jobs:
  - template: win-wasm-ci.yml
    parameters:
      CommitOverride: true
      BuildConfig: 'Release'
      ExtraBuildArgs: '${{ parameters.ExtraBuildArgs }}'
      PoolName: onnxruntime-Ubuntu2004-AMD-CPU
      SkipPublish: true
      TimeoutInMinutes: 270
